FROM python:latest

WORKDIR /app

COPY ../api/requirements.txt /app/requirements.txt
COPY ../api/app.py /app/app.py

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]